---
driver:
  name: vagrant
  customize:
    cpus: 2

provisioner:
  name: chef_zero

platforms:
  - name: chef/centos-6.6

suites:
  - name: default
    run_list:
      - recipe[consul::default]
    attributes:
